# Generated by Django 5.2.6 on 2025-09-13 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('negocio', 'Negocio'), ('cliente', 'Cliente')], default='negocio', max_length=20),
        ),
    ]
