# Generated by Django 5.2.6 on 2025-09-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('negocio', 'Negocio'), ('cliente', 'Cliente')], default='cliente', max_length=20),
        ),
    ]
