# Generated by Django 5.2.6 on 2025-09-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negocio', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('servicio', models.CharField(max_length=100)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
            ],
        ),
    ]
